language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm
install: npm install
jobs:
  include:
    - stage: test
      script: bash ./travis/test.sh
    - stage: build
      if: type = push
      script: bash ./travis/build.sh
      script: bash ./travis/pushback.sh
dist: trusty
sudo: true